import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header/Header";
 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` font-sans antialiased`}
      >
     <div className="min-h-screen flex flex-col justify-between items-center px-4 max-w-6xl mx-auto">
          <Header/>
          {children}
    
       </div>
      </body>
    </html>
  );
}
